name: getdash
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter



  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  get: ^4.6.5
  shared_preferences: ^2.1.0
#  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.9
  firebase_core: ^2.17.0
  path_provider: ^2.0.14
  country_code_picker: ^3.0.0
  universal_platform: ^1.0.0+1
  image_picker: ^0.8.5+3
  cached_network_image: ^3.3.0
  shimmer_animation: ^2.1.0+1
  file_picker: ^5.3.0
  fl_chart: ^0.62.0
  dotted_border: ^2.0.0+3
  data_table_2: ^2.5.3
  google_maps_flutter: ^2.5.0
  appflowy_board: ^0.1.1
  calendar_view: ^1.0.4
  flutter_colorpicker: ^1.0.3
  badges: ^3.1.2
  flutter_charts: ^0.5.2
  syncfusion_flutter_charts:
  d_chart: ^2.6.3
  flutter_svg: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/language/
    - img/

